package com.aprendendo.javacore.o_exception.runtime.test;

public class RuntimeExceptionTest4 {
	public static void main(String[] args) {
		try {
			
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("Dentro do ArrayIndexOutOfBoundsException");
		}
	}
}
